
import __ASTRO_IMAGE_IMPORT_1SjmwC from "/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_1aovVP from "/src/images/blog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_rtFm3 from "/src/images/blog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_ZgqadJ from "/src/images/blog/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_Z1HfQoj from "/src/images/blog/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_pF9b from "/src/images/blog/a-vibrant-cel-shaded-illustration-of-a-vault-hunte.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgaming-borderlands-the-satifying-looter-shooter-1.md";
import __ASTRO_IMAGE_IMPORT_ZYl0Nw from "/src/images/blog/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_1Y8VSu from "/src/images/blog/a-dynamic-cel-shaded-illustration-featuring-four-i.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgaming-borderlands-the-satifying-looter-shooter.md";
import __ASTRO_IMAGE_IMPORT_7VzKP from "/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FHealth_%26_Wellness-5_Natural_Supplements_to_Boost_Your_Immune_System_in_2025.md";
import __ASTRO_IMAGE_IMPORT_2jDz48 from "/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FMarketing_Technology-How_AI-Generated_Video_Ads_Are_Revolutionizing_Digital_Marketing_in_2025.md";
import __ASTRO_IMAGE_IMPORT_29qw0N from "/src/images/blog/a-clean-minimalist-digital-planner-interface-named.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fproductivity-and-lifestyle-clutterclear-the-minimalist-digit.md";
import __ASTRO_IMAGE_IMPORT_Zf7mLB from "/src/images/blog/a-serene-minimalist-digital-interface-showing-a-ca.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fproductivity-and-lifestyle-zencycle-the-minimalist-mood-and.md";
export default new Map([["/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_1SjmwC], ["/src/images/blog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_1aovVP], ["/src/images/blog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_rtFm3], ["/src/images/blog/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_ZgqadJ], ["/src/images/blog/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_Z1HfQoj], ["/src/images/blog/a-vibrant-cel-shaded-illustration-of-a-vault-hunte.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgaming-borderlands-the-satifying-looter-shooter-1.md", __ASTRO_IMAGE_IMPORT_pF9b], ["/src/images/blog/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_ZYl0Nw], ["/src/images/blog/a-dynamic-cel-shaded-illustration-featuring-four-i.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgaming-borderlands-the-satifying-looter-shooter.md", __ASTRO_IMAGE_IMPORT_1Y8VSu], ["/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FHealth_%26_Wellness-5_Natural_Supplements_to_Boost_Your_Immune_System_in_2025.md", __ASTRO_IMAGE_IMPORT_7VzKP], ["/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FMarketing_Technology-How_AI-Generated_Video_Ads_Are_Revolutionizing_Digital_Marketing_in_2025.md", __ASTRO_IMAGE_IMPORT_2jDz48], ["/src/images/blog/a-clean-minimalist-digital-planner-interface-named.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fproductivity-and-lifestyle-clutterclear-the-minimalist-digit.md", __ASTRO_IMAGE_IMPORT_29qw0N], ["/src/images/blog/a-serene-minimalist-digital-interface-showing-a-ca.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fproductivity-and-lifestyle-zencycle-the-minimalist-mood-and.md", __ASTRO_IMAGE_IMPORT_Zf7mLB]]);
		